kind: pipeline
type: kubernetes
name: build
steps:
- name: docker
  image: harbor.k-space.ee/k-space/drone-kaniko
  settings:
    repo: ${DRONE_REPO}
    tags: latest
    registry: harbor.codemowers.eu
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
